Repository elizenai/SAP007-burger-queen-api-client, pull requests merged in 2022-06, with the labels that each got.

#21 Send order to kitchen
  src/pages/Saloon/index.jsx
  src/services/api.js
Labels: feat

#22 refactor: msg error
  src/pages/Login/index.jsx
  src/services/error.js
Labels: refactor

#23 Feat/add orders amount
  src/pages/Saloon/index.jsx
  src/pages/Saloon/style.css
Labels: feat

#24 Add flavor and complement
  src/components/Command/index.jsx
  src/components/ProductCard/index.jsx
  src/pages/Saloon/index.jsx
Labels: feat

#25 Try add function logout
  src/pages/Saloon/index.jsx
Labels: bug

#26 Feat/add logout
  src/components/Header/index.jsx
  src/pages/Saloon/index.jsx
  src/services/filter.js
Labels: feat, refactor

#27 Feat/style saloon
  package-lock.json
  package.json
  src/components/Button/style.css
  src/components/Header/index.jsx
  src/components/Header/style.css
  src/components/Input/style.css
  src/pages/Register/style.css
  src/pages/Saloon/index.jsx
  src/pages/Saloon/style.css
Labels: feat

#28 Add style btn
  src/components/Button/style.css
  src/components/Input/style.css
  src/pages/Saloon/style.css
Labels: feat

#29 Feat/tests register login
  src/setupTests.js
  src/tests/Button.test.jsx
  src/tests/Input.test.jsx
  src/tests/ProductCard.test.jsx
  src/tests/Register.test.jsx
Labels: feat

#30 Bug initialize saloon and reset command after order
  src/components/Select/index.jsx
  src/pages/Saloon/index.jsx
  src/services/api.js
Labels: bug

#31 Feat/page kitchen
  src/components/OrdersKitchen/index.jsx
  src/pages/Kitchen/index.jsx
  src/services/api.js
Labels: feat

#32 component kitchen
  src/components/OrdersKitchen/index.jsx
  src/pages/Kitchen/index.jsx
Labels: feat

#36 Feat/format date
  package-lock.json
  package.json
  src/components/OrdersKitchen/index.jsx
  src/pages/Kitchen/index.jsx
  src/services/formatTime.js
Labels: bug, feat

#37 Feat/page kitchen
  src/components/OrdersKitchen/style.css
  src/components/ProductCard/style.css
  src/pages/Saloon/index.jsx
  src/pages/Saloon/style.css
Labels: feat

#40 Add page ready orders
  src/components/OrdersKitchen/index.jsx
  src/pages/Kitchen/index.jsx
  src/pages/ReadyOrders/index.jsx
  src/pages/Saloon/index.jsx
  src/routes.jsx
Labels: feat

#41 Feat/private route
  src/routes.jsx
  src/services/api.js
Labels: feat

#43 Docs: add readme
  README.old.md
  public/burger.gif
  public/cadastro.png
  public/foto_Eli.jpg
  public/foto_Gabi.jpg
  public/kitchen.png
  public/login.png
  public/saloon.png
  public/trello.png
Labels: documentation

#44 Docs update Readme
  README.md
  README.old.md
Labels: documentation

#45 Update images Readme
  README.md
Labels: documentation

#47 docs: update info readme
  README.md
  src/img/burger.gif
  src/img/cadastro.png
  src/img/foto-Eli.jpg
  src/img/foto-Gabi.jpg
  src/img/kitchen.png
  src/img/login.png
  src/img/luke.gif
  src/img/saloon.png
  src/img/trello.png
Labels: documentation

#49 Feat sort order kitchen and readyOrders
  src/pages/Kitchen/index.jsx
  src/pages/ReadyOrders/index.jsx
  src/services/formatTime.js
  src/services/sortOrder.js
Labels: feat
